### ISSUE TITLE
can't run the example in my vps 

### ISSUE THREAD

**Issue by motconvoi** [Creased/relative-path-overwrite#1]
Hello @Creased,

Thank you very much for the example, but I can't manage to run it on my VPS server.

 * Tested URL: `//example.com/relative-path-overwrite/upload/..%2F`
 * Response:

    ```
    Not Found
    The requested URL /relative-path-overwrite/upload/../ was not found on this server.
    ```

Can you help me solve this issue?

**Comment by Creased** [comment]
Are you running the demo on Apache HTTPd? It's only applicable when `AllowEncodedSlashes` is set to `On`.

Thanks for your feedback.

**Comment by motconvoi** [comment]
thanks you very much, i got it. 
Do you have any RPO attack examples?

**Comment by Creased** [comment]
Hi, I've discovered this attack while doing Bug Hunting on associative BB
program from HackerOne.

I've designed a challenge based on this attack for a Capture the Flag
contest, if you want to check it out you just need to fetch sources and run
it with Docker ([Sources](https://gitlab.com/Areizen/ctf-1a-2018)).

The challenge is dubbed HaRPOon and implements a bot that'll be able to
handle you RPO attack. Please note that this challenge has been bypassed
using a simple HTML file upload, but IMHO it's a realistic demo 😉

**Comment by Creased** [comment]
Hi, I've discovered this attack while doing Bug Hunting on associative BB
program from HackerOne.


I've designed a challenge based on this attack for a Capture the Flag
contest, if you want to check it out you just need to fetch sources and run
it with Docker (https://gitlab.com/Areizen/ctf-1a-2018).


The challenge is dubbed HaRPOon and implements a bot that'll be able to
handle you RPO attack. Please note that this challenge has been bypassed
using a simple HTML file upload, but IMHO it's a realistic demo 😉

**Comment by Creased** [comment]
Thanks again for your report!

Since the issue has been clarified, I'll go ahead and close, but feel free to ask me if you need more information!

**Comment by Creased** [comment]
Thanks again for your report!

Since the issue has been clarified, I'll go ahead and close, but feel free to ask me if you need more information!
